version: '3'
services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    networks:
      - db_network
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: quizdb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4:7
    volumes:
      - pgadmindata:/var/lib/pgadmin4/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: root@example.com
      PGADMIN_DEFAULT_PASSWORD: root
      TZ: Asia/Tokyo
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - db_network
networks:
  db_network:
volumes:
  postgres-data:
  pgadmindata:
